"""address table deleted

Revision ID: 0c8b31395efc
Revises: 3910cb318116
Create Date: 2025-06-15 15:20:36.655824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c8b31395efc'
down_revision: Union[str, None] = '3910cb318116'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('addresses')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('address_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('country', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('street', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('house', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('apartment', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('postal_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('addresses_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('addresses_pkey'))
    )
    # ### end Alembic commands ###
